---
title: "income inequlaity model"
author: Naveed Ahmad
execute: 
  echo: false

---

```{r}
#| message: false
#| warning: false
#| results: 'hide'
library(tidycensus)
library(tidyverse)
library(tidymodels)
library(broom)
library(ggrepel)
library(plotly)
library(marginaleffects)
```

```{r}
#| message: false
#| warning: false
multi_vars <- c(
  gini = "B19083_001",
  median_income = "B19013_001",
  poverty = "B17001_002")

  socio_data <- get_acs(
  geography = "state",
  variables = multi_vars,
  year = 2020,
  survey = "acs5",
  output = "wide")

  socio_clean <- socio_data |> 
  transmute(
    state = NAME,
    gini = giniE,
    median_income = median_incomeE,
    poverty = povertyE)
```

```{r}
#| message: false
#| warning: false
# Build interactive plot
plot_ly(socio_clean,
  x = ~median_income,
  y = ~gini,
  type = "scatter",
  mode = "markers",
  text = ~paste(
    "<b>State:</b>", state,
    "<br><b>Gini Index:</b>", round(gini, 3),
    "<br><b>Median Income:</b> $", formatC(median_income, format = "d", big.mark = ""),
    "<br><b>Poverty:</b>", formatC(poverty, format = "d", big.mark = ",")),
  hoverinfo = "text",
  marker = list(
    size = ~sqrt(poverty) / 40,  # Adjusted for visual scale
    color = ~gini,
    colorscale = "Blues",
    showscale = TRUE,
    line = list(width = 1, color = "#FFFFFF"))) %>%
  layout(
    title = "Income Inequality vs Median Income (Interactive)",
    xaxis = list(title = "Median Household Income (USD)"),
    yaxis = list(title = "Gini Index"),
    hoverlabel = list(bgcolor = "white", font = list(size = 12)))
```



## Model

$$
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_n X_n + \epsilon
$$

with $\epsilon \sim \mathcal{N}(0, \sigma^2)$.


The estimated linear regression model is:
$$
\hat{gini} = 0.65 - 0.03 \cdot \log(\text{median\_income}) + 0.01 \cdot \log(\text{poverty})
$$


```{r}
Income_ineq_model <- linear_reg(engine = "lm") |> 
   fit(gini ~ log(median_income) + log(poverty), data = socio_clean)
  
```

```{r}
plot_predictions(Income_ineq_model, by = "median_income")
print(plot_predictions)
```


```{r}
plot_predictions(Income_ineq_model, by = "poverty")
print(plot_predictions)
```